/**
 * Enums for Event Planner API
 */

export enum EventType {
  CONFERENCE = 'CONFERENCE',
  WORKSHOP = 'WORKSHOP',
  SEMINAR = 'SEMINAR',
  MEETING = 'MEETING',
  PARTY = 'PARTY',
  WEDDING = 'WEDDING',
  BIRTHDAY = 'BIRTHDAY',
  CORPORATE_EVENT = 'CORPORATE_EVENT',
  TRADE_SHOW = 'TRADE_SHOW',
  CONCERT = 'CONCERT',
  FESTIVAL = 'FESTIVAL',
  SPORTS_EVENT = 'SPORTS_EVENT',
  CHARITY_EVENT = 'CHARITY_EVENT',
  NETWORKING = 'NETWORKING',
  TRAINING = 'TRAINING',
  RETREAT = 'RETREAT',
  OTHER = 'OTHER'
}

export enum EventStatus {
  DRAFT = 'DRAFT',
  PLANNING = 'PLANNING',
  PUBLISHED = 'PUBLISHED',
  REGISTRATION_OPEN = 'REGISTRATION_OPEN',
  REGISTRATION_CLOSED = 'REGISTRATION_CLOSED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  POSTPONED = 'POSTPONED'
}

export enum EventUserType {
  ORGANIZER = 'ORGANIZER',
  COORDINATOR = 'COORDINATOR',
  ATTENDEE = 'ATTENDEE',
  VOLUNTEER = 'VOLUNTEER',
  VENDOR = 'VENDOR',
  SPEAKER = 'SPEAKER',
  SPONSOR = 'SPONSOR',
  MEDIA = 'MEDIA',
  STAFF = 'STAFF',
  COLLABORATOR = 'COLLABORATOR',
  ADMIN = 'ADMIN'
}

export enum EventNotificationChannel {
  EMAIL = 'EMAIL',
  SMS = 'SMS',
  PUSH = 'PUSH',
  IN_APP = 'IN_APP'
}

export enum EventNotificationPriority {
  LOW = 'LOW',
  NORMAL = 'NORMAL',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL'
}

export enum UserType {
  INDIVIDUAL = 'INDIVIDUAL',
  ORGANIZATION = 'ORGANIZATION',
  ADMIN = 'ADMIN'
}
