/**
 * Enums for Event Planner API
 */

export enum EventType {
  CONFERENCE = 'CONFERENCE',
  WORKSHOP = 'WORKSHOP',
  SEMINAR = 'SEMINAR',
  MEETING = 'MEETING',
  PARTY = 'PARTY',
  WEDDING = 'WEDDING',
  BIRTHDAY = 'BIRTHDAY',
  CORPORATE_EVENT = 'CORPORATE_EVENT',
  TRADE_SHOW = 'TRADE_SHOW',
  CONCERT = 'CONCERT',
  FESTIVAL = 'FESTIVAL',
  SPORTS_EVENT = 'SPORTS_EVENT',
  CHARITY_EVENT = 'CHARITY_EVENT',
  NETWORKING = 'NETWORKING',
  TRAINING = 'TRAINING',
  RETREAT = 'RETREAT',
  OTHER = 'OTHER'
}

export enum EventStatus {
  DRAFT = 'DRAFT',
  PLANNING = 'PLANNING',
  PUBLISHED = 'PUBLISHED',
  REGISTRATION_OPEN = 'REGISTRATION_OPEN',
  REGISTRATION_CLOSED = 'REGISTRATION_CLOSED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  POSTPONED = 'POSTPONED'
}

export enum UserType {
  INDIVIDUAL = 'INDIVIDUAL',
  ORGANIZATION = 'ORGANIZATION',
  ADMIN = 'ADMIN'
}
